# Dataset stats

This is a notebook to get statistics (size, composition) on each dataset we have, so we can better contexualize our findings and potentially spot shortcomings.

In [1]:
%load_ext autoreload
%autoreload 2

### Imports

In [ ]:
import polars as pl
from pathlib import Path
from scipy.stats import mode
from project.utils.functions import load_config

### Specify what datasets to look at

In [3]:
datasets = [
    # "protein properties"
	"prot_param",
    "uniprot_topology",
    # Dependent largely on linear sequence (?)
	"interpro_conserved_site",
	"interpro_repeat",
    "uniprot_peptide",
    "uniprot_post_translational_modification",
    "uniprot_phosphorylation",
    "uniprot_lipidation",
	"biomap_localization_prediction",
    # # Secondary structure
    "biomap_ssp_q3",
    "biomap_ssp_q8",
	"uniprot_secondary_structure",
    # # Dependent largely on tertiary structure
    "uniprot_functional_sites",
	"interpro_binding_site",
	"biomap_metal_ion_binding",
	"interpro_active_site",
    "interpro_domain",
    "interpro_family",
    "interpro_homologous_superfamily",
    # # Dependent on cellular context
    "GO_cc",
    "GO_mf",
    "GO_bp",
]

### Read datasets and extract size, train:val:test counts, and other stats

In [4]:

dataset_stats = []
label_distributions = []

for dataset_name in datasets:
    try:
        config = load_config(dataset_name)
        df = pl.read_parquet(config['data_path'].replace('/network/scratch/s', '/home/mila/s'))
        if 'targets' in df.columns:
            feats = len(df['targets'].list.explode().unique())
        else:   
            feats = len([c for c in df.columns if df[c].dtype != pl.String])

        samples = len(df)
        frac_train= df['split'].value_counts(normalize=True).filter(pl.col('split') == 'train')['proportion'].item()
        frac_val = df['split'].value_counts(normalize=True).filter(pl.col('split') == 'val')['proportion'].item()
        frac_test = df['split'].value_counts(normalize=True).filter(pl.col('split') == 'test')['proportion'].item()
        if config['task_level'] == 'protein_level':
            annotations_per_protein = df[[c for c in df.columns if (df[c].dtype==pl.Boolean)]].sum_horizontal()
            average_num_annotations = annotations_per_protein.mean()
            std_num_annotations = annotations_per_protein.std()
            annotation_group_sizes = df[[c for c in df.columns if (df[c].dtype==pl.Boolean)]].sum().to_numpy()
            smallest_group_size = annotation_group_sizes.min()
            biggest_group_size = annotation_group_sizes.max()
            mode_group_size = mode(annotation_group_sizes, axis=1, keepdims=False).mode.item()
            group_sizes_mean = annotation_group_sizes.mean()
            group_sizes_std = annotation_group_sizes.std()
        else:
            # We'll just fudge this instead of counting annotations at amino acid level, because they're not really comparable (e.g. all amino acids in a domain)
            average_num_annotations, std_num_annotations = 0.0, 0.0
            smallest_group_size, biggest_group_size, mode_group_size, group_sizes_mean, group_sizes_std = 0.0, 0.0, 0.0, 0.0, 0.0

        dataset_stats.append( {
            'dataset': config['dataset_name'],
            'task_level': config['task_level'],
            'task_type': config['task_type'],
            'num_samples': samples,
            'num_features': feats,
            'average_num_annotations': f"{average_num_annotations:.2f} \u00B1 {std_num_annotations:.2f}",
            'group_min_mode_max': f"[{smallest_group_size},{mode_group_size},{biggest_group_size}]",
            'average_group_size': f"{group_sizes_mean:.2f}",
            'split': f"{frac_train:.2f} : {frac_val:.2f} : {frac_test:.2f}",
        })
    except Exception as e:

        dataset_stats.append( {
            'dataset': config['dataset_name'],
            'task_level': config['task_level'],
            'task_type': config['task_type'],
            'num_samples': samples,
            'num_features': feats,
            'average_num_annotations': 0.0,
            'group_min_max': f"[0,0]",
            'average_group_size': f"{0.0}",
            'split': f"{frac_train:.2f} : {frac_val:.2f} : {frac_test:.2f}",
        })
        
        print(dataset_name)
        print(e)
        continue

prot_param
`std` operation not supported for dtype `str`
biomap_localization_prediction
`std` operation not supported for dtype `str`
biomap_metal_ion_binding
`std` operation not supported for dtype `str`

In [5]:
pl.DataFrame(dataset_stats)

shape: (22, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ dataset   ┆ task_leve ┆ task_type ┆ num_sampl ┆ … ┆ group_min ┆ average_g ┆ split     ┆ group_mi │
│ ---       ┆ l         ┆ ---       ┆ es        ┆   ┆ _max      ┆ roup_size ┆ ---       ┆ n_mode_m │
│ str       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ax       │
│           ┆ str       ┆           ┆ i64       ┆   ┆ str       ┆ str       ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ prot_para ┆ protein_l ┆ regressio ┆ 18126     ┆ … ┆ [0,0]     ┆ 0.0       ┆ 0.70 :    ┆ null     │
│ m         ┆ evel      ┆ n         ┆           ┆   ┆           ┆           ┆ 0.15 :    ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0.14      ┆          │
│ uniprot_t ┆ amino_aci ┆ multiclas ┆ 4777      ┆ … ┆ null      ┆ 0.00      ┆ 0.71 :    ┆ [0.0,0.0 │
│ opology   ┆ d_level   ┆ s_classif ┆           ┆   ┆           ┆           ┆ 0.16 :    ┆ ,0.0]    │
│           ┆           ┆ ication   ┆           ┆   ┆           ┆           ┆ 0.14      ┆          │
│ interpro_ ┆ protein_l ┆ binary_cl ┆ 2948      ┆ … ┆ null      ┆ 9.49      ┆ 0.70 :    ┆ [2,2,185 │
│ conserved ┆ evel      ┆ assificat ┆           ┆   ┆           ┆           ┆ 0.15 :    ┆ ]        │
│ _site     ┆           ┆ ion       ┆           ┆   ┆           ┆           ┆ 0.15      ┆          │
│ interpro_ ┆ protein_l ┆ binary_cl ┆ 1189      ┆ … ┆ null      ┆ 23.37     ┆ 0.69 :    ┆ [2,2,209 │
│ repeat    ┆ evel      ┆ assificat ┆           ┆   ┆           ┆           ┆ 0.16 :    ┆ ]        │
│           ┆           ┆ ion       ┆           ┆   ┆           ┆           ┆ 0.15      ┆          │
│ uniprot_p ┆ amino_aci ┆ multiclas ┆ 4977      ┆ … ┆ null      ┆ 0.00      ┆ 0.70 :    ┆ [0.0,0.0 │
│ eptide    ┆ d_level   ┆ s_classif ┆           ┆   ┆           ┆           ┆ 0.14 :    ┆ ,0.0]    │
│           ┆           ┆ ication   ┆           ┆   ┆           ┆           ┆ 0.16      ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ interpro_ ┆ protein_l ┆ binary_cl ┆ 3601      ┆ … ┆ null      ┆ 18.89     ┆ 0.58 :    ┆ [2,4,716 │
│ family    ┆ evel      ┆ assificat ┆           ┆   ┆           ┆           ┆ 0.19 :    ┆ ]        │
│           ┆           ┆ ion       ┆           ┆   ┆           ┆           ┆ 0.23      ┆          │
│ interpro_ ┆ protein_l ┆ binary_cl ┆ 8198      ┆ … ┆ null      ┆ 117.81    ┆ 0.67 :    ┆ [13,21,8 │
│ homologou ┆ evel      ┆ assificat ┆           ┆   ┆           ┆           ┆ 0.17 :    ┆ 44]      │
│ s_superfa ┆           ┆ ion       ┆           ┆   ┆           ┆           ┆ 0.16      ┆          │
│ mil…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ GO_cc     ┆ protein_l ┆ binary_cl ┆ 16443     ┆ … ┆ null      ┆ 52.59     ┆ 0.69 :    ┆ [0,2,499 │
│           ┆ evel      ┆ assificat ┆           ┆   ┆           ┆           ┆ 0.15 :    ┆ 0]       │
│           ┆           ┆ ion       ┆           ┆   ┆           ┆           ┆ 0.16      ┆          │
│ GO_mf     ┆ protein_l ┆ binary_cl ┆ 11504     ┆ … ┆ null      ┆ 16.10     ┆ 0.70 :    ┆ [0,2,184 │
│           ┆ evel      ┆ assificat ┆           ┆   ┆           ┆           ┆ 0.16 :    ┆ 3]       │
│           ┆           ┆ ion       ┆           ┆   ┆           ┆           ┆ 0.15      ┆          │
│ GO_bp     ┆ protein_l ┆ binary_cl ┆ 12255     ┆ … ┆ null      ┆ 12.32     ┆ 0.70 :    ┆ [0,2,130 │
│           ┆ evel      ┆ assificat ┆           ┆   ┆           ┆           ┆ 0.15 :    ┆ 5]       │
│           ┆           ┆ ion       ┆           ┆   ┆           ┆           ┆ 0.14      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

We've noticed that for some datasets, taking normalized embeddings and running them through a probe that was trained on original embeddings actually seems to give higher performance on our output metric (matthews correlation coefficient). Is there a correlation between particular datasets, and whether the norm was higher or lower?

In [6]:
# Identify which datasets have norm higher than original embeddings
norm_higher_map = {
    'prot_param': False,
    'uniprot_lipidation': True,
    'uniprot_topology': True,
    'uniprot_peptide': True,
    'uniprot_functional_sites': True,
    'uniprot_phosphorylation': False,
    'uniprot_secondary_structure': True,
    'biomap_ssp_q3': True,
    'biomap_ssp_q8': True,
    'biomap_metal_ion_binding': False,
    'biomap_localization_prediction': False,
    'uniprot_post_translational_modification': True,
    'interpro_binding_site': False,
    'interpro_active_site': False,
    'interpro_repeat': False,
    'interpro_conserved_site': False,
    'interpro_family': False,
    'interpro_homologous_superfamily': False,
    'interpro_domain': False,
    'GO_mf': False,
    'GO_bp': False,
    'GO_cc': False
}

# We need to add a categorical column to be able to do correlations
data_summary_df = pl.DataFrame(dataset_stats).with_columns(
    pl.col('task_level').cast(pl.Categorical).cast(pl.Int16).alias("task_level_categorical"),
    pl.col('task_type').cast(pl.Categorical).cast(pl.Int16).alias("task_type_categorical"),
    ).sort(by=['task_level', 'task_type', 'num_samples']).with_columns(
        pl.col('dataset').replace_strict(norm_higher_map).alias('norm_higher')
    ).with_columns(
        ~pl.col('norm_higher').alias('norm_lower')
    )

In [7]:
data_summary_df

shape: (22, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ dataset   ┆ task_leve ┆ task_type ┆ num_sampl ┆ … ┆ task_leve ┆ task_type ┆ norm_high ┆ norm_low │
│ ---       ┆ l         ┆ ---       ┆ es        ┆   ┆ l_categor ┆ _categori ┆ er        ┆ er       │
│ str       ┆ ---       ┆ str       ┆ ---       ┆   ┆ ical      ┆ cal       ┆ ---       ┆ ---      │
│           ┆ str       ┆           ┆ i64       ┆   ┆ ---       ┆ ---       ┆ bool      ┆ bool     │
│           ┆           ┆           ┆           ┆   ┆ i16       ┆ i16       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ uniprot_l ┆ amino_aci ┆ multiclas ┆ 978       ┆ … ┆ 1         ┆ 3         ┆ true      ┆ false    │
│ ipidation ┆ d_level   ┆ s_classif ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ication   ┆           ┆   ┆           ┆           ┆           ┆          │
│ uniprot_t ┆ amino_aci ┆ multiclas ┆ 4777      ┆ … ┆ 1         ┆ 3         ┆ true      ┆ false    │
│ opology   ┆ d_level   ┆ s_classif ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ication   ┆           ┆   ┆           ┆           ┆           ┆          │
│ uniprot_p ┆ amino_aci ┆ multiclas ┆ 4977      ┆ … ┆ 1         ┆ 3         ┆ true      ┆ false    │
│ eptide    ┆ d_level   ┆ s_classif ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ication   ┆           ┆   ┆           ┆           ┆           ┆          │
│ uniprot_f ┆ amino_aci ┆ multiclas ┆ 6893      ┆ … ┆ 1         ┆ 3         ┆ true      ┆ false    │
│ unctional ┆ d_level   ┆ s_classif ┆           ┆   ┆           ┆           ┆           ┆          │
│ _sites    ┆           ┆ ication   ┆           ┆   ┆           ┆           ┆           ┆          │
│ uniprot_p ┆ amino_aci ┆ multiclas ┆ 8648      ┆ … ┆ 1         ┆ 3         ┆ false     ┆ true     │
│ hosphoryl ┆ d_level   ┆ s_classif ┆           ┆   ┆           ┆           ┆           ┆          │
│ ation     ┆           ┆ ication   ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ GO_mf     ┆ protein_l ┆ binary_cl ┆ 11504     ┆ … ┆ 0         ┆ 4         ┆ false     ┆ true     │
│           ┆ evel      ┆ assificat ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ion       ┆           ┆   ┆           ┆           ┆           ┆          │
│ GO_bp     ┆ protein_l ┆ binary_cl ┆ 12255     ┆ … ┆ 0         ┆ 4         ┆ false     ┆ true     │
│           ┆ evel      ┆ assificat ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ion       ┆           ┆   ┆           ┆           ┆           ┆          │
│ GO_cc     ┆ protein_l ┆ binary_cl ┆ 16443     ┆ … ┆ 0         ┆ 4         ┆ false     ┆ true     │
│           ┆ evel      ┆ assificat ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ion       ┆           ┆   ┆           ┆           ┆           ┆          │
│ biomap_lo ┆ protein_l ┆ multiclas ┆ 7530      ┆ … ┆ 0         ┆ 3         ┆ false     ┆ true     │
│ calizatio ┆ evel      ┆ s_classif ┆           ┆   ┆           ┆           ┆           ┆          │
│ n_predict ┆           ┆ ication   ┆           ┆   ┆           ┆           ┆           ┆          │
│ ion       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ prot_para ┆ protein_l ┆ regressio ┆ 18126     ┆ … ┆ 0         ┆ 2         ┆ false     ┆ true     │
│ m         ┆ evel      ┆ n         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
data_summary_df.write_csv(Path('/home/mila/s/shawn.whitfield/scratch/results/dataset_characterization') / 'datasets_summary.csv')

In [9]:
data_summary_df[['task_level_categorical', 'task_type_categorical', 'num_samples', 'num_features', 'norm_higher', 'norm_lower']].corr()

shape: (6, 6)
┌─────────────────────┬────────────────────┬─────────────┬──────────────┬─────────────┬────────────┐
│ task_level_categori ┆ task_type_categori ┆ num_samples ┆ num_features ┆ norm_higher ┆ norm_lower │
│ cal                 ┆ cal                ┆ ---         ┆ ---          ┆ ---         ┆ ---        │
│ ---                 ┆ ---                ┆ f64         ┆ f64          ┆ f64         ┆ f64        │
│ f64                 ┆ f64                ┆             ┆              ┆             ┆            │
╞═════════════════════╪════════════════════╪═════════════╪══════════════╪═════════════╪════════════╡
│ 1.0                 ┆ -0.649722          ┆ 0.059361    ┆ -0.286899    ┆ 0.908514    ┆ -0.908514  │
│ -0.649722           ┆ 1.0                ┆ -0.366981   ┆ 0.321162     ┆ -0.590281   ┆ 0.590281   │
│ 0.059361            ┆ -0.366981          ┆ 1.0         ┆ 0.281112     ┆ 0.044992    ┆ -0.044992  │
│ -0.286899           ┆ 0.321162           ┆ 0.281112    ┆ 1.0          ┆ -0.260466   ┆ 0.260466   │
│ 0.908514            ┆ -0.590281          ┆ 0.044992    ┆ -0.260466    ┆ 1.0         ┆ -1.0       │
│ -0.908514           ┆ 0.590281           ┆ -0.044992   ┆ 0.260466     ┆ -1.0        ┆ 1.0        │
└─────────────────────┴────────────────────┴─────────────┴──────────────┴─────────────┴────────────┘

It looks like there's a strong correlation between the task level and whether the norm is higher or lower.